(() => {
  const c = window.INVITATION_CONFIG;
  if (!c) return;
  const $ = (id) => document.getElementById(id);
  const text = (id, value) => { const el = $(id); if (el) el.textContent = value ?? ""; };
  const esc = (s) => String(s).replace(/[&<>"']/g, (ch) => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[ch]));
  const ar = (n) => String(n).replace(/[0-9]/g, d => "٠١٢٣٤٥٦٧٨٩"[Number(d)]);
  const { baby, parents, reception: r } = c;
  if (baby.gender) document.body.classList.add(`tint-${baby.gender}`);
  document.title = `بشارة مولود — ${baby.nameArabic}`;
  const metaTitle = document.querySelector('meta[property="og:title"]');
  const metaDescription = document.querySelector('meta[property="og:description"]');
  const metaImage = document.querySelector('meta[property="og:image"]');
  if (metaTitle) metaTitle.content = document.title;
  if (metaDescription) metaDescription.content = `بشرى سارة بقدوم ${baby.nameArabic}`;
  if (metaImage && c.assets?.coverShareImage) metaImage.content = new URL(c.assets.coverShareImage, window.location.href).href;
  text("babyName", baby.nameArabic); text("babyNameEnglish", baby.nameEnglish); text("heroGreet", `أهلاً بـ ${baby.nameArabic}`); text("birthDate", `تاريخ الميلاد: ${baby.birthDateText}`);
  text("parentsLine", `بفرحٍ من والديه ${parents.father} و${parents.mother}`);
  text("invitationText", r.invitationText); text("venueDate", r.dateText); text("venueTime", r.timeText); text("venueName", r.venueName); text("venueAddr", r.venueAddress); text("closingNote", r.closingNote); text("closingHashtag", r.hashtag); text("closingHost", `بدعوة من ${parents.family}`);
  $("mapBtn").href = r.mapUrl;
  const phone = r.whatsAppUrl;
  if (phone) { $("contactBox").hidden = false; text("contactLabel",r.contactLabel); text("contactLink",r.contactName); $("contactLink").href=phone; $("contactLink").target="_blank"; $("contactLink").rel="noopener"; }
  $("timeline").innerHTML = r.program.map(x => `<li class="timeline__item"><span class="timeline__dot" aria-hidden="true"></span><span class="timeline__time">${esc(x.time)}</span><span class="timeline__title">${esc(x.title)}</span></li>`).join("");
  $("notesList").innerHTML = r.notes.map((x,i) => `<li class="notes__item"><span class="notes__mark" aria-hidden="true">${["🌙","⭐","🍼","✨"][i%4]}</span><span>${esc(x)}</span></li>`).join("");
  $("wishList").innerHTML = r.existingWishes.map((x,i) => `<article class="wish"><div class="wish-av" style="background:${["#9a86d8","#e6c878","#7d90c9","#b8a8e8","#d8c08a"][i%5]}">${esc([...x.name][0])}</div><div class="wish-body"><div class="wish-name">${esc(x.name)}</div><div class="wish-msg">${esc(x.message)}</div></div></article>`).join("");
  $("prayerList").innerHTML = c.prayers.map(p => `<article class="prayer-card"><p>﴿${esc(p.text)}﴾</p><a href="${esc(p.url)}" target="_blank" rel="noopener">${esc(p.source)} · القرآن الكريم</a></article>`).join("");
  text("hadithText", `«${c.hadith.text}»`); text("hadithSource", c.hadith.source); $("hadithSource").href = c.hadith.url;
  setupCalendar(); setupCountdown(); setupCover(); setupReveals(); setupRsvp(); createStars("coverStars",38); createStars("skyStars",48);
  function setupCover(){ $("openBtn").addEventListener("click",()=>{ $("cover").classList.add("is-open"); $("invite").setAttribute("aria-hidden","false"); document.querySelector(".hero").classList.add("is-visible"); window.scrollTo({top:0,behavior:"smooth"}); }); }
  function createStars(id,count){ const layer=$(id); if(matchMedia("(prefers-reduced-motion: reduce)").matches)return; for(let i=0;i<count;i++){const s=document.createElement("span");s.style.left=`${Math.random()*100}%`;s.style.top=`${Math.random()*100}%`;s.style.width=s.style.height=`${1.5+Math.random()*2.6}px`;s.style.animationDelay=`${Math.random()*5}s`;s.style.animationDuration=`${2+Math.random()*4}s`;layer.appendChild(s);} }
  function setupReveals(){const items=document.querySelectorAll(".reveal:not(.hero)");if(!("IntersectionObserver" in window)){items.forEach(e=>e.classList.add("is-visible"));return;}const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("is-visible");observer.unobserve(e.target);}}),{threshold:.12});items.forEach(e=>observer.observe(e));}
  function setupCountdown(){const end=new Date(r.date).getTime();const tick=()=>{let d=Math.max(0,end-Date.now());if(d===0){$("countdown").hidden=true;$("cdArrived").hidden=false;return;}const vals=[Math.floor(d/86400000),Math.floor(d/3600000)%24,Math.floor(d/60000)%60,Math.floor(d/1000)%60];["cdDays","cdHours","cdMins","cdSecs"].forEach((id,i)=>text(id,ar(String(vals[i]).padStart(2,"0"))));};tick();setInterval(tick,1000);}
  function setupCalendar(){const d=new Date(r.date);const end=new Date(d.getTime()+4*3600000);text("calendarMonth",new Intl.DateTimeFormat("ar",{month:"long",year:"numeric",timeZone:"Asia/Baghdad"}).format(d));text("calendarDay",ar(new Intl.DateTimeFormat("en-GB",{day:"2-digit",timeZone:"Asia/Baghdad"}).format(d)));text("calendarTime",r.timeText);const stamp=(date)=>{const parts=new Intl.DateTimeFormat("en-GB",{timeZone:r.timeZone||"Asia/Baghdad",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hourCycle:"h23"}).formatToParts(date).reduce((o,p)=>(o[p.type]=p.value,o),{});return `${parts.year}${parts.month}${parts.day}T${parts.hour}${parts.minute}${parts.second}`;};const localStart=stamp(d),localEnd=stamp(end);const start=d.toISOString().replace(/[-:]/g,"").replace(/\.\d{3}Z$/, "Z"),finish=end.toISOString().replace(/[-:]/g,"").replace(/\.\d{3}Z$/, "Z");const title=`بشارة مولود ${baby.nameArabic}`;const location=`${r.venueName} — ${r.venueAddress}`;const details=`${r.invitationText}\n${location}`;$("googleCalendar").href=`https://calendar.google.com/calendar/render?action=TEMPLATE&text=${encodeURIComponent(title)}&dates=${localStart}/${localEnd}&ctz=${encodeURIComponent(r.timeZone||"Asia/Baghdad")}&location=${encodeURIComponent(location)}&details=${encodeURIComponent(details)}`;const ics=["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//Baby Celebration//AR","BEGIN:VEVENT",`DTSTART:${start}`,`DTEND:${finish}`,`SUMMARY:${title}`,`LOCATION:${location}`,`DESCRIPTION:${details.replace(/\n/g,"\\n")}`,"END:VEVENT","END:VCALENDAR"].join("\r\n");$("downloadCalendar").href=URL.createObjectURL(new Blob([ics],{type:"text/calendar;charset=utf-8"}));}
  function setupRsvp(){let attending="yes",count=0;document.querySelectorAll("#attendance .pill").forEach(b=>b.addEventListener("click",()=>{attending=b.dataset.v;document.querySelectorAll("#attendance .pill").forEach(x=>x.setAttribute("aria-pressed",String(x===b)));}));$("plus").addEventListener("click",()=>{count=Math.min(20,count+1);text("guestCount",ar(count));});$("minus").addEventListener("click",()=>{count=Math.max(0,count-1);text("guestCount",ar(count));});$("rsvpForm").addEventListener("submit",e=>{e.preventDefault();const name=$("guestName").value.trim();if(!name)return;const note=$("wishText").value.trim();const result=attending==="yes"?"تم تسجيل تأكيد حضورك محلياً، شكراً لكم 🤍":attending==="no"?"شكراً لإبلاغنا، سنفتقدكم 🤍":"تم تسجيل ردّكم محلياً، شكراً لكم 🤍";text("formMessage",result+(note?` — وصلت تهنئتك: ${note}`:""));});}
})();
